// package com.example.ime.keys

// import com.example.ime.R
// data class Symbol(
//     val text: String,
//     val keyId: Int,
//     val popupKeys:String ="",
//     val isEnabled: Boolean = true,
//     val weight: Float = 1.0f 
// )
// val EN= listOf(
//     Symbol("a", R.id.keyA,"@,&"),
//     Symbol("b", R.id.keyB),
//     Symbol("c", R.id.keyC),
//     Symbol("d", R.id.keyD),
//     Symbol("e", R.id.keyE),
//     Symbol("f", R.id.keyF),
//     Symbol("g", R.id.keyG),
//     Symbol("h", R.id.keyH),
//     Symbol("i", R.id.keyI),
//     Symbol("j", R.id.keyJ),
//     Symbol("k", R.id.keyK),
//     Symbol("l", R.id.keyL),
//     Symbol("m", R.id.keyM),
//     Symbol("n", R.id.keyN),
//     Symbol("o", R.id.keyO),
//     Symbol("p", R.id.keyP),
//     Symbol("q", R.id.keyQ),
//     Symbol("r", R.id.keyR),
//     Symbol("s", R.id.keyS),
//     Symbol("t", R.id.keyT),
//     Symbol("u", R.id.keyU),
//     Symbol("v", R.id.keyV),
//     Symbol("w", R.id.keyW),
//     Symbol("x", R.id.keyX),
//     Symbol("y", R.id.keyY),
//     Symbol("z", R.id.keyZ),
//     Symbol("ش", R.id.keySh),
//     Symbol("ط", R.id.keyTa),
//     Symbol("ظ", R.id.keyTha),
// )
// val AR = listOf(
//     Symbol("س", R.id.keyA),
//     Symbol("و", R.id.keyB),
//     Symbol("ز", R.id.keyC),
//     Symbol("ب", R.id.keyD),
//     Symbol("ق", R.id.keyE),
//     Symbol("ل", R.id.keyF),
//     Symbol("ا", R.id.keyG),
//     Symbol("ت", R.id.keyH),
//     Symbol("خ", R.id.keyI),
//     Symbol("ن", R.id.keyJ),
//     Symbol("م", R.id.keyK),
//     Symbol("ك", R.id.keyL),
//     Symbol("ث", R.id.keyM),
//     Symbol("ة", R.id.keyN),
//     Symbol("ح", R.id.keyO),
//     Symbol("ج", R.id.keyP),
//     Symbol("ض", R.id.keyQ),
//     Symbol("ف", R.id.keyR),
//     Symbol("ي", R.id.keyS),
//     Symbol("غ", R.id.keyT),
//     Symbol("ه", R.id.keyU),
//     Symbol("ر", R.id.keyV),
//     Symbol("ص", R.id.keyW),
//     Symbol("د", R.id.keyX),
//     Symbol("ع", R.id.keyY),
//     Symbol("ذ", R.id.keyZ),
//     Symbol("ش", R.id.keySh),
//     Symbol("ط", R.id.keyTa),
//     Symbol("ظ", R.id.keyTha,"a,b"),
// )
// data class KeyData(
//     val keyId: String,
//     val text: String,
//     val popupKeys: List<String>
// )
